import "./globals.css";

export const metadata = {
  title: "MieBaso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const currentScroll = () => {
    if (scrollY > 0) {
      alert("berhasil");
    }
  };
  return (
    <html lang="en">
      <body>{children} </body>
    </html>
  );
}
